name: frame_virtual_fiscilation
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  get: ^4.7.2
  flutter_svg: ^2.0.17
  # local-storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.5
  collection:
  flutter_screenutil: ^5.9.0
  google_fonts:
  dotted_border:
  image_picker: ^1.1.2
  path:
  intl:
  flutter_speed_dial: ^7.0.0
  device_info_plus: ^10.0.0
  http:
  url_launcher: ^6.3.2
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/splash/
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets\fonts\Satoshi-Light.ttf
          weight: 300
        - asset: assets\fonts\Satoshi-Regular.ttf
          weight: 400
        - asset: assets\fonts\Satoshi-Medium.ttf
          weight: 500
        - asset: assets\fonts\Satoshi-Bold.ttf
          weight: 700
        - asset: assets\fonts\Satoshi-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
